// @generated by pi-protocol generate; DO NOT EDIT.
// contract-digest: sha256:6919f9a503331ce893eb8e55c2ab689dff9c611b654925c4c06e31e2e52eaa3f
import type { ProtocolAgentExecutor, ProtocolHandler } from "@kybernetria/pi-protocol/core";

export const PROTOCOL_NODE_ID = "pi_dev" as const;
export const PROTOCOL_TARGETS = {
  scout: "pi_dev.scout",
  architect: "pi_dev.architect",
  worker: "pi_dev.worker",
  reviewer: "pi_dev.reviewer",
  security_reviewer: "pi_dev.security_reviewer",
} as const;

export type ProtocolProvideName = "scout" | "architect" | "worker" | "reviewer" | "security_reviewer";
export type ProtocolBinding = ProtocolHandler | ProtocolAgentExecutor;
export type ProtocolBindings = {
  "scout": ProtocolBinding;
  "architect": ProtocolBinding;
  "worker": ProtocolBinding;
  "reviewer": ProtocolBinding;
  "security_reviewer": ProtocolBinding;
};

export type ScoutInput = { context?: string; questions?: readonly string[]; scope?: readonly string[]; task: string; };
export type ScoutOutput = { codePaths: readonly { from: string; relationship: string; to: string; }[]; diagnostics: readonly string[]; files: readonly { line?: number; path: string; relevance: string; }[]; findings: readonly string[]; message: string; summary: string; unresolvedQuestions: readonly string[]; };
export type ArchitectInput = { constraints?: readonly string[]; context?: string; task: string; };
export type ArchitectOutput = { acceptanceCriteria: readonly string[]; assumptions: readonly string[]; diagnostics: readonly string[]; message: string; plan: readonly { action: string; order: number; rationale: string; }[]; risks: readonly { mitigation: string; risk: string; }[]; summary: string; };
export type WorkerInput = { acceptanceCriteria?: readonly string[]; context?: string; plan?: readonly string[]; task: string; };
export type WorkerOutput = { changedFiles: readonly { change: string; path: string; }[]; diagnostics: readonly string[]; message: string; summary: string; tests: readonly ({ command: string; output: string; status: "passed" | "failed" | "skipped"; })[]; unresolvedIssues: readonly string[]; };
export type ReviewerInput = { acceptanceCriteria?: readonly string[]; commit?: string; context?: string; diff?: string; range?: string; task: string; testExpectations?: readonly string[]; };
export type ReviewerOutput = { diagnostics: readonly string[]; findings: readonly ({ explanation: string; file: string; line?: number; recommendedFix: string; severity: "blocker" | "high" | "medium" | "low" | "info"; })[]; message: string; summary: string; testResults: readonly ({ command: string; output: string; status: "passed" | "failed" | "skipped"; })[]; verdict: "approve" | "request_changes" | "blocked"; };
export type SecurityReviewerInput = { acceptanceCriteria?: readonly string[]; commit?: string; context?: string; diff?: string; range?: string; securityFocus?: readonly string[]; task: string; testExpectations?: readonly string[]; };
export type SecurityReviewerOutput = { diagnostics: readonly string[]; findings: readonly ({ area: string; explanation: string; exploitability: "none" | "low" | "medium" | "high"; file: string; line?: number; recommendedFix: string; severity: "blocker" | "high" | "medium" | "low" | "info"; })[]; message: string; summary: string; testResults: readonly ({ command: string; output: string; status: "passed" | "failed" | "skipped"; })[]; threatModel: readonly { asset: string; mitigation: string; threat: string; }[]; verdict: "approve" | "request_changes" | "blocked"; };
